// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("PSlogger")>]
[<assembly: AssemblyProductAttribute("PSlogger")>]
[<assembly: AssemblyDescriptionAttribute("Azure logger using table storage")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "PSlogger"
    let [<Literal>] AssemblyProduct = "PSlogger"
    let [<Literal>] AssemblyDescription = "Azure logger using table storage"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
